sudo: false
language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'

install:
  - npm install
  - npm install -g codecov

script:
  - npm run build

after_success:
  - npm run coverage
  - codecov
